# Generated by Django 5.2.15 on 2026-06-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama produk')),
                ('slug', models.SlugField(blank=True, help_text='Otomatis dari nama bila dikosongkan.', max_length=120, unique=True)),
                ('subtitle', models.CharField(help_text='Contoh: Manajemen Bisnis Retail', max_length=150, verbose_name='Subjudul')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('icon', models.CharField(default='bi bi-box-seam', help_text='Kelas Bootstrap Icons, contoh: bi bi-box-seam, bi bi-tools, bi bi-shop', max_length=60, verbose_name='Ikon')),
                ('features', models.TextField(blank=True, help_text='Satu fitur per baris (tekan Enter untuk fitur berikutnya).', verbose_name='Fitur')),
                ('link', models.CharField(default='/service-details/', help_text="Tujuan tombol 'Pelajari Lebih Lanjut'.", max_length=200, verbose_name='Tautan tombol')),
                ('order', models.PositiveIntegerField(default=0, help_text='Makin kecil makin awal.', verbose_name='Urutan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Tampilkan')),
            ],
            options={
                'verbose_name': 'Produk',
                'verbose_name_plural': 'Produk',
                'ordering': ['order', 'id'],
            },
        ),
    ]
