# Generated by Django 5.2.15 on 2026-06-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='link',
        ),
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.TextField(blank=True, help_text='Manfaat, fungsi, dan cara kerja aplikasi — tampil di halaman detail produk.', verbose_name='Penjelasan Lengkap'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Gambar besar di halaman detail produk (opsional).', upload_to='produk/', verbose_name='Gambar halaman detail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Teks pendek yang tampil di kartu beranda.', verbose_name='Deskripsi singkat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text='Satu fitur per baris (tekan Enter untuk fitur berikutnya).', verbose_name='Fitur Utama'),
        ),
    ]
