# Generated by Django 5.2.15 on 2026-07-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_link_product_detail_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='logo',
            field=models.ImageField(blank=True, help_text='Opsional. Bila diisi, menggantikan ikon di kartu & halaman detail.', upload_to='produk/logo/', verbose_name='Logo produk'),
        ),
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.CharField(default='bi bi-box-seam', help_text='Kelas Bootstrap Icons (dipakai bila Logo dikosongkan). Contoh: bi bi-box-seam, bi bi-tools, bi bi-shop', max_length=60, verbose_name='Ikon'),
        ),
    ]
