"""
Django settings for imogi project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Frontend (static HTML pages + assets) lives one level up, in the project root.
FRONTEND_DIR = BASE_DIR.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ceju-+zcb01c2ik+yx03$c=e13972n&e1s))4sf2_)bktsoar&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Tema admin Unfold (harus sebelum django.contrib.admin)
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Local apps
    'blog',
    'contact',
    'products',
    'school',
    'clients',
    'testimonials',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'imogi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates', FRONTEND_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'products.context_processors.products',
                'school.context_processors.materials',
                'clients.context_processors.clients',
                'testimonials.context_processors.testimonials',
            ],
        },
    },
]

WSGI_APPLICATION = 'imogi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'id'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Frontend assets (CSS/JS/img) are served from the project root /assets folder,
# matching the existing references in the HTML (assets/...).
STATIC_URL = '/assets/'
STATICFILES_DIRS = [FRONTEND_DIR / 'assets']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media (uploaded files, e.g. blog images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------
# Email
# ---------------------------------------------------------------------------
# Dev: emails are printed to the console (terminal running runserver).
# For production, switch to SMTP and fill the credentials below.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.example.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'imogi.indonesia@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-password'

DEFAULT_FROM_EMAIL = 'Imogi Indonesia <imogi.indonesia@gmail.com>'

# Where contact-form notifications are sent.
CONTACT_NOTIFY_EMAIL = 'imogi.indonesia@gmail.com'

# ---------------------------------------------------------------------------
# Unfold — tampilan admin modern (branding Imogi Indonesia)
# ---------------------------------------------------------------------------
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    'SITE_TITLE': 'Admin Imogi Indonesia',
    'SITE_HEADER': 'Imogi Indonesia',
    'SITE_SUBHEADER': 'PT. Inovasi Terbaik Bangsa',
    'SITE_URL': '/',
    'DASHBOARD_CALLBACK': 'imogi.dashboard.dashboard_callback',
    'SITE_LOGO': lambda request: static('img/logo.png'),
    'SITE_ICON': lambda request: static('img/favicon.png'),
    'SITE_SYMBOL': 'inventory_2',
    'SHOW_HISTORY': True,
    'SHOW_VIEW_ON_SITE': True,
    'SHOW_LANGUAGES': False,
    'BORDER_RADIUS': '8px',

    # Aksen merah kalem (maroon) untuk admin — lebih elegan, tidak menyala
    'COLORS': {
        'primary': {
            '50': '250 244 244',
            '100': '246 228 228',
            '200': '237 201 202',
            '300': '222 162 164',
            '400': '199 108 110',
            '500': '176 42 44',
            '600': '150 35 37',
            '700': '122 30 32',
            '800': '101 28 30',
            '900': '84 27 28',
            '950': '47 13 13',
        },
    },

    'SIDEBAR': {
        'show_search': True,
        'show_all_applications': True,
        'navigation': [
            {
                'title': _('Navigasi'),
                'separator': True,
                'items': [
                    {
                        'title': _('Dasbor'),
                        'icon': 'dashboard',
                        'link': reverse_lazy('admin:index'),
                    },
                    {
                        'title': _('Lihat Situs'),
                        'icon': 'public',
                        'link': '/',
                    },
                ],
            },
            {
                'title': _('Konten'),
                'separator': True,
                'items': [
                    {
                        'title': _('Produk'),
                        'icon': 'inventory_2',
                        'link': reverse_lazy('admin:products_product_changelist'),
                    },
                    {
                        'title': _('Klien'),
                        'icon': 'handshake',
                        'link': reverse_lazy('admin:clients_client_changelist'),
                    },
                    {
                        'title': _('Testimoni'),
                        'icon': 'format_quote',
                        'link': reverse_lazy('admin:testimonials_testimonial_changelist'),
                    },
                    {
                        'title': _('Materi (Imogi School)'),
                        'icon': 'school',
                        'link': reverse_lazy('admin:school_material_changelist'),
                    },
                    {
                        'title': _('Artikel'),
                        'icon': 'newspaper',
                        'link': reverse_lazy('admin:blog_blogpost_changelist'),
                    },
                    {
                        'title': _('Kategori'),
                        'icon': 'sell',
                        'link': reverse_lazy('admin:blog_category_changelist'),
                    },
                ],
            },
            {
                'title': _('Interaksi'),
                'separator': True,
                'items': [
                    {
                        'title': _('Pesan Kontak'),
                        'icon': 'mail',
                        'link': reverse_lazy('admin:contact_contactmessage_changelist'),
                    },
                ],
            },
            {
                'title': _('Sistem'),
                'separator': True,
                'items': [
                    {
                        'title': _('Pengguna'),
                        'icon': 'person',
                        'link': reverse_lazy('admin:auth_user_changelist'),
                    },
                    {
                        'title': _('Grup'),
                        'icon': 'group',
                        'link': reverse_lazy('admin:auth_group_changelist'),
                    },
                ],
            },
        ],
    },
}
