# Generated by Django 5.2.15 on 2026-06-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nama')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Subjek')),
                ('message', models.TextField(verbose_name='Pesan')),
                ('is_read', models.BooleanField(default=False, verbose_name='Sudah dibaca')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dikirim pada')),
            ],
            options={
                'verbose_name': 'Pesan Kontak',
                'verbose_name_plural': 'Pesan Kontak',
                'ordering': ['-created_at'],
            },
        ),
    ]
