# Generated by Django 5.2.15 on 2026-06-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='company',
            field=models.CharField(blank=True, max_length=150, verbose_name='Perusahaan'),
        ),
    ]
