# Generated by Django 5.2.15 on 2026-06-29 06:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nama kategori')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul')),
                ('slug', models.SlugField(blank=True, help_text='Otomatis dari judul bila dikosongkan.', max_length=220, unique=True)),
                ('author', models.CharField(default='Tim Imogi Indonesia', max_length=100, verbose_name='Penulis')),
                ('image', models.ImageField(blank=True, upload_to='blog/', verbose_name='Gambar utama')),
                ('excerpt', models.TextField(help_text='Teks pendek yang tampil di kartu daftar artikel.', max_length=300, verbose_name='Ringkasan')),
                ('content', models.TextField(help_text='Boleh memakai HTML sederhana (h3, p, blockquote, dll).', verbose_name='Isi artikel')),
                ('is_published', models.BooleanField(default=True, verbose_name='Tayang')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal tayang')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
                'ordering': ['-published_at'],
            },
        ),
    ]
