# Generated by Django 5.2.15 on 2026-06-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='Tulis & format dengan toolbar (tebal, judul, daftar, tautan) — tanpa perlu kode.', verbose_name='Isi artikel'),
        ),
    ]
