# Generated by Django 5.2.15 on 2026-06-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Judul materi')),
                ('link', models.CharField(help_text='URL materi — boleh eksternal (YouTube/PDF/Drive) atau halaman situs.', max_length=300, verbose_name='Tautan')),
                ('order', models.PositiveIntegerField(default=0, help_text='Makin kecil makin awal.', verbose_name='Urutan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Tampilkan')),
            ],
            options={
                'verbose_name': 'Materi',
                'verbose_name_plural': 'Materi',
                'ordering': ['order', 'id'],
            },
        ),
    ]
