# Generated by Django 5.2.15 on 2026-06-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, help_text='Unggah file materi (mis. PDF). Kosongkan jika memakai tautan.', upload_to='materi/', verbose_name='File materi'),
        ),
        migrations.AlterField(
            model_name='material',
            name='link',
            field=models.CharField(blank=True, help_text='Link YouTube/TikTok/Drive, dll. Kosongkan jika mengunggah file.', max_length=300, verbose_name='Tautan eksternal'),
        ),
    ]
