# Generated by Django 5.2.15 on 2026-07-01 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nama')),
                ('role', models.CharField(help_text='Contoh: Direktur Operasional', max_length=120, verbose_name='Jabatan')),
                ('company', models.CharField(help_text='Contoh: PT Tiga Perkasa Teknik', max_length=150, verbose_name='Perusahaan')),
                ('photo', models.ImageField(help_text='Foto orang yang memberi testimoni.', upload_to='testimoni/', verbose_name='Foto')),
                ('logo', models.ImageField(blank=True, help_text='Opsional. Tampil sebagai chip putih kecil di testimoni.', upload_to='testimoni/logo/', verbose_name='Logo perusahaan')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Jumlah bintang (1–5).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('quote', models.TextField(verbose_name='Kutipan testimoni')),
                ('order', models.PositiveIntegerField(default=0, help_text='Makin kecil makin awal.', verbose_name='Urutan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Tampilkan')),
            ],
            options={
                'verbose_name': 'Testimoni',
                'verbose_name_plural': 'Testimoni',
                'ordering': ['order', 'id'],
            },
        ),
    ]
