# Generated by Django 5.2.15 on 2026-07-01 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='logo',
        ),
    ]
