# Generated by Django 5.2.15 on 2026-07-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nama klien')),
                ('logo', models.ImageField(help_text='Logo klien. Disarankan PNG latar transparan.', upload_to='klien/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, help_text='Opsional — tautan ke situs klien.', verbose_name='Website')),
                ('order', models.PositiveIntegerField(default=0, help_text='Makin kecil makin awal.', verbose_name='Urutan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Tampilkan')),
            ],
            options={
                'verbose_name': 'Klien',
                'verbose_name_plural': 'Klien',
                'ordering': ['order', 'id'],
            },
        ),
    ]
